//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSoapHumanCycle.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHumanCycle")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Human", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHumanCycle.Model")]
    [System.SerializableAttribute()]
    public partial class Human : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Human[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HumanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Human[] ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Slice SliceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Statut StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Town TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Human[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HumanId {
            get {
                return this.HumanIdField;
            }
            set {
                if ((this.HumanIdField.Equals(value) != true)) {
                    this.HumanIdField = value;
                    this.RaisePropertyChanged("HumanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Human[] Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Slice Slice {
            get {
                return this.SliceField;
            }
            set {
                if ((object.ReferenceEquals(this.SliceField, value) != true)) {
                    this.SliceField = value;
                    this.RaisePropertyChanged("Slice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Statut Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Town Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHumanCycle.Model")]
    [System.SerializableAttribute()]
    public partial class Gender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Human[] HumansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenderId {
            get {
                return this.GenderIdField;
            }
            set {
                if ((this.GenderIdField.Equals(value) != true)) {
                    this.GenderIdField = value;
                    this.RaisePropertyChanged("GenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Human[] Humans {
            get {
                return this.HumansField;
            }
            set {
                if ((object.ReferenceEquals(this.HumansField, value) != true)) {
                    this.HumansField = value;
                    this.RaisePropertyChanged("Humans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Slice", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHumanCycle.Model")]
    [System.SerializableAttribute()]
    public partial class Slice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Human[] HumansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SliceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Human[] Humans {
            get {
                return this.HumansField;
            }
            set {
                if ((object.ReferenceEquals(this.HumansField, value) != true)) {
                    this.HumansField = value;
                    this.RaisePropertyChanged("Humans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SliceId {
            get {
                return this.SliceIdField;
            }
            set {
                if ((this.SliceIdField.Equals(value) != true)) {
                    this.SliceIdField = value;
                    this.RaisePropertyChanged("SliceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statut", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHumanCycle.Model")]
    [System.SerializableAttribute()]
    public partial class Statut : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Human[] HumansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatutIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Human[] Humans {
            get {
                return this.HumansField;
            }
            set {
                if ((object.ReferenceEquals(this.HumansField, value) != true)) {
                    this.HumansField = value;
                    this.RaisePropertyChanged("Humans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatutId {
            get {
                return this.StatutIdField;
            }
            set {
                if ((this.StatutIdField.Equals(value) != true)) {
                    this.StatutIdField = value;
                    this.RaisePropertyChanged("StatutId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Town", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHumanCycle.Model")]
    [System.SerializableAttribute()]
    public partial class Town : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientSoapHumanCycle.ServiceReference1.Human[] HumansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TownIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientSoapHumanCycle.ServiceReference1.Human[] Humans {
            get {
                return this.HumansField;
            }
            set {
                if ((object.ReferenceEquals(this.HumansField, value) != true)) {
                    this.HumansField = value;
                    this.RaisePropertyChanged("Humans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TownId {
            get {
                return this.TownIdField;
            }
            set {
                if ((this.TownIdField.Equals(value) != true)) {
                    this.TownIdField = value;
                    this.RaisePropertyChanged("TownId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClientSoapHumanCycle.ServiceReference1.CompositeType GetDataUsingDataContract(ClientSoapHumanCycle.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClientSoapHumanCycle.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHumen", ReplyAction="http://tempuri.org/IService1/GetHumenResponse")]
        ClientSoapHumanCycle.ServiceReference1.Human[] GetHumen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHumen", ReplyAction="http://tempuri.org/IService1/GetHumenResponse")]
        System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human[]> GetHumenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnLastHuman", ReplyAction="http://tempuri.org/IService1/ReturnLastHumanResponse")]
        ClientSoapHumanCycle.ServiceReference1.Human ReturnLastHuman();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnLastHuman", ReplyAction="http://tempuri.org/IService1/ReturnLastHumanResponse")]
        System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human> ReturnLastHumanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateHuman", ReplyAction="http://tempuri.org/IService1/CreateHumanResponse")]
        ClientSoapHumanCycle.ServiceReference1.Human CreateHuman(string lastName, string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateHuman", ReplyAction="http://tempuri.org/IService1/CreateHumanResponse")]
        System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human> CreateHumanAsync(string lastName, string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateHuman", ReplyAction="http://tempuri.org/IService1/UpdateHumanResponse")]
        ClientSoapHumanCycle.ServiceReference1.Human UpdateHuman(ClientSoapHumanCycle.ServiceReference1.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateHuman", ReplyAction="http://tempuri.org/IService1/UpdateHumanResponse")]
        System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human> UpdateHumanAsync(ClientSoapHumanCycle.ServiceReference1.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGenderList", ReplyAction="http://tempuri.org/IService1/InsertGenderListResponse")]
        void InsertGenderList(ClientSoapHumanCycle.ServiceReference1.Gender[] genders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertGenderList", ReplyAction="http://tempuri.org/IService1/InsertGenderListResponse")]
        System.Threading.Tasks.Task InsertGenderListAsync(ClientSoapHumanCycle.ServiceReference1.Gender[] genders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertHumanList", ReplyAction="http://tempuri.org/IService1/InsertHumanListResponse")]
        void InsertHumanList(ClientSoapHumanCycle.ServiceReference1.Human[] humen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertHumanList", ReplyAction="http://tempuri.org/IService1/InsertHumanListResponse")]
        System.Threading.Tasks.Task InsertHumanListAsync(ClientSoapHumanCycle.ServiceReference1.Human[] humen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStatutList", ReplyAction="http://tempuri.org/IService1/InsertStatutListResponse")]
        void InsertStatutList(ClientSoapHumanCycle.ServiceReference1.Statut[] statuts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertStatutList", ReplyAction="http://tempuri.org/IService1/InsertStatutListResponse")]
        System.Threading.Tasks.Task InsertStatutListAsync(ClientSoapHumanCycle.ServiceReference1.Statut[] statuts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSliceList", ReplyAction="http://tempuri.org/IService1/InsertSliceListResponse")]
        void InsertSliceList(ClientSoapHumanCycle.ServiceReference1.Slice[] slices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSliceList", ReplyAction="http://tempuri.org/IService1/InsertSliceListResponse")]
        System.Threading.Tasks.Task InsertSliceListAsync(ClientSoapHumanCycle.ServiceReference1.Slice[] slices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTownList", ReplyAction="http://tempuri.org/IService1/InsertTownListResponse")]
        void InsertTownList(ClientSoapHumanCycle.ServiceReference1.Town[] towns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertTownList", ReplyAction="http://tempuri.org/IService1/InsertTownListResponse")]
        System.Threading.Tasks.Task InsertTownListAsync(ClientSoapHumanCycle.ServiceReference1.Town[] towns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllTables", ReplyAction="http://tempuri.org/IService1/DeleteAllTablesResponse")]
        void DeleteAllTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllTables", ReplyAction="http://tempuri.org/IService1/DeleteAllTablesResponse")]
        System.Threading.Tasks.Task DeleteAllTablesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientSoapHumanCycle.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientSoapHumanCycle.ServiceReference1.IService1>, ClientSoapHumanCycle.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClientSoapHumanCycle.ServiceReference1.CompositeType GetDataUsingDataContract(ClientSoapHumanCycle.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClientSoapHumanCycle.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ClientSoapHumanCycle.ServiceReference1.Human[] GetHumen() {
            return base.Channel.GetHumen();
        }
        
        public System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human[]> GetHumenAsync() {
            return base.Channel.GetHumenAsync();
        }
        
        public ClientSoapHumanCycle.ServiceReference1.Human ReturnLastHuman() {
            return base.Channel.ReturnLastHuman();
        }
        
        public System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human> ReturnLastHumanAsync() {
            return base.Channel.ReturnLastHumanAsync();
        }
        
        public ClientSoapHumanCycle.ServiceReference1.Human CreateHuman(string lastName, string firstName) {
            return base.Channel.CreateHuman(lastName, firstName);
        }
        
        public System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human> CreateHumanAsync(string lastName, string firstName) {
            return base.Channel.CreateHumanAsync(lastName, firstName);
        }
        
        public ClientSoapHumanCycle.ServiceReference1.Human UpdateHuman(ClientSoapHumanCycle.ServiceReference1.Human human) {
            return base.Channel.UpdateHuman(human);
        }
        
        public System.Threading.Tasks.Task<ClientSoapHumanCycle.ServiceReference1.Human> UpdateHumanAsync(ClientSoapHumanCycle.ServiceReference1.Human human) {
            return base.Channel.UpdateHumanAsync(human);
        }
        
        public void InsertGenderList(ClientSoapHumanCycle.ServiceReference1.Gender[] genders) {
            base.Channel.InsertGenderList(genders);
        }
        
        public System.Threading.Tasks.Task InsertGenderListAsync(ClientSoapHumanCycle.ServiceReference1.Gender[] genders) {
            return base.Channel.InsertGenderListAsync(genders);
        }
        
        public void InsertHumanList(ClientSoapHumanCycle.ServiceReference1.Human[] humen) {
            base.Channel.InsertHumanList(humen);
        }
        
        public System.Threading.Tasks.Task InsertHumanListAsync(ClientSoapHumanCycle.ServiceReference1.Human[] humen) {
            return base.Channel.InsertHumanListAsync(humen);
        }
        
        public void InsertStatutList(ClientSoapHumanCycle.ServiceReference1.Statut[] statuts) {
            base.Channel.InsertStatutList(statuts);
        }
        
        public System.Threading.Tasks.Task InsertStatutListAsync(ClientSoapHumanCycle.ServiceReference1.Statut[] statuts) {
            return base.Channel.InsertStatutListAsync(statuts);
        }
        
        public void InsertSliceList(ClientSoapHumanCycle.ServiceReference1.Slice[] slices) {
            base.Channel.InsertSliceList(slices);
        }
        
        public System.Threading.Tasks.Task InsertSliceListAsync(ClientSoapHumanCycle.ServiceReference1.Slice[] slices) {
            return base.Channel.InsertSliceListAsync(slices);
        }
        
        public void InsertTownList(ClientSoapHumanCycle.ServiceReference1.Town[] towns) {
            base.Channel.InsertTownList(towns);
        }
        
        public System.Threading.Tasks.Task InsertTownListAsync(ClientSoapHumanCycle.ServiceReference1.Town[] towns) {
            return base.Channel.InsertTownListAsync(towns);
        }
        
        public void DeleteAllTables() {
            base.Channel.DeleteAllTables();
        }
        
        public System.Threading.Tasks.Task DeleteAllTablesAsync() {
            return base.Channel.DeleteAllTablesAsync();
        }
    }
}
